add ctftime api client
g0tiu5a/g0tiu5a-bot pull request #11
Opened 2017-06-20 13:12 UTC by tukeJonny

ctftimesからCTFに関する情報をAPIで取得するクライアントの実装をした
確認お願いします 🙇

2017-06-20 15:02 UTC, ryosan-470 requested changes
GitHub上でのコミットした人がお前誰状況になっているので、GitHubに登録してあるメールアドレスでコミットしてください。

コメントが消えると困るのでリベースせずこの上に修正コミットを積んでください。

2017-06-20 15:02 UTC, ryosan-470 commented on ctftimes/event.go
> +	common.Decode(response, &events)
ここのerr処理が忘れているっぽい

2017-06-20 15:02 UTC, ryosan-470 commented on sample.go
> +package main
テスト用だと思いますが不要です。もし載せるのであればテストコードを書きましょう。

2017-06-20 15:02 UTC, ryosan-470 commented on ctftimes/event.go
> +	url := URL_PREFIX + "/events/?limit=" + LIMIT + "&start=" + fmt.Sprintf("%v", now)
好みかもしれませんがこう書くなら全部 `fmt.Sprintf` で書いても良かったかもしれません。

また、最後の `fmt.Sprintf("%v", now)` は駄目だと思います。Stringに直すべきだと思います。(`%v`は控えたほうがいいかと)
https://golang.org/pkg/time/#Time.Format

2017-06-20 15:02 UTC, ryosan-470 commented on ctftimes/event.go
> +// event
コメント不要

2017-06-20 15:02 UTC, ryosan-470 commented on ctftimes/event.go
> +package ctftimes
ディレクトリ名とパッケージ名は `ctftime` です。複数形ではないです。
(もし、Coffeeのほうがそうなっているのであればそれはミスです。許してください)

2017-06-20 15:04 UTC, nwiizo commented on ctftimes/event.go
> +// event
良さそう

2017-06-20 15:08 UTC, ryosan-470 commented on ctftimes/event.go
> +	"github.com/tukejonny/g0tiu5a-bot/common"
インポートパス間違ってるw

```diff
- github.com/tukejonny/g0tiu5a-bot/common
+ github.com/g0tiu5a/g0tiu5a-bot/common
```
 ですね

2017-06-20 15:09 UTC, ryosan-470 commented on ctftimes/event.go
> +// event
一般論ですがこういう一見してコメントすべきことではないことまでコメントする必要はありません。

リーダブルコード5章を読みましょう。

2017-06-20 15:41 UTC, tukeJonny commented on ctftimes/event.go
> +package ctftimes
や、僕が勝手にやっただけですw
直します〜

2017-06-20 15:42 UTC, tukeJonny commented on ctftimes/event.go
> +// event
了解！
消しときます〜

ちなみに、他にコメントが必要だけど書いてない部分とかあったりしたら教えてもらえると嬉しいです〜

2017-06-20 15:47 UTC, tukeJonny commented on ctftimes/event.go
> +	url := URL_PREFIX + "/events/?limit=" + LIMIT + "&start=" + fmt.Sprintf("%v", now)
確かにそうですね・・・
直しときますー

2017-06-20 15:49 UTC, tukeJonny commented on ctftimes/event.go
> +	common.Decode(response, &events)
マジですね
Decode内でエラー処理してくれるって想定で書いちゃってる
確認してみたらエラー返してるだけなので、こっちでハンドリングしなくちゃいけないですね

ううん・・・
統一したほうがいいとは思うんだけど、一貫性持たせるならDecode()内でハンドリングしたほうが良いかな？

2017-06-20 15:50 UTC, tukeJonny commented on sample.go
> +package main
了解です〜
event_test.go書くようにしますー

2017-06-20 15:50 UTC, tukeJonny commented on ctftimes/event.go
> +	"github.com/tukejonny/g0tiu5a-bot/common"
直します〜

2017-06-21 00:01 UTC, ryosan-470 commented on ctftimes/event.go
> +// event
特に煩雑なロジックはないのですべてコメント不要かと

2017-06-26 22:57 UTC, closed without merging

2017-06-27 01:44 UTC, ryosan-470 commented
こっちクローズしたのかよw #12