ctftimesからCTFに関する情報をAPIで取得するクライアント機能追加
g0tiu5a/g0tiu5a-bot pull request #12
Opened 2017-06-26 22:59 UTC by tukeJonny

前回のプルリクから修正を加え、テストを追加してみましたー
確認よろしくお願いいたします！🙇

2017-06-27 10:41 UTC, ryosan-470 requested changes
コミットした人がGitHubのアカウントとリンクされていないのでその部分直してくださいませ。

2017-06-27 10:41 UTC, ryosan-470 commented on common/util.go
> +	//decode
前回を書いたようなきがするけど、コメント不要だよー :joy:

2017-06-27 10:41 UTC, ryosan-470 commented on common/util.go
> +		//log.Fatal(body)
不要

2017-06-27 10:41 UTC, ryosan-470 commented on common/util.go
> +	//check
不要

2017-06-27 10:41 UTC, ryosan-470 commented on common/util_test.go
> +	// Open json_file for testing
コメント不要です。

2017-06-27 10:41 UTC, ryosan-470 commented on common/util_test.go
> +	// Create HTTP Response
このコメントは残しておきましょうか。もう少し詳しく書いてもいいかもしれませんが

2017-06-27 10:41 UTC, ryosan-470 commented on ctftime/event.go
> +	url := URL_PREFIX + "/events/?limit=" + strconv.Itoa(LIMIT) + "&start=" + strconv.FormatInt(now, 10)
前回と比べて見やすくなったと思います。まあ強いて言えばですが、`LIMIT` が `int` であるなら、

```go
"%d", LIMIT
``` 

とかでもよかったかもしれませんが

2017-06-27 10:41 UTC, ryosan-470 commented on ctftime/event_test.go
> +	"github.com/tukejonny/g0tiu5a-bot/common"
ああー直っていないorz

2017-06-27 10:42 UTC, ryosan-470 commented
<img width="342" alt="screen shot 2017-06-27 at 19 40 49" src="https://user-images.githubusercontent.com/5006625/27583807-a42c0ec6-5b70-11e7-8030-6647012356fd.png">

こうなっていると誰がコミットしたのかわからんのとGitHubで芝を生やせないよw

2017-06-27 14:24 UTC, tukeJonny commented on common/util.go
> +	//decode
消しましたー

2017-06-27 14:25 UTC, tukeJonny commented on common/util.go
> +		//log.Fatal(body)
消しましたー

2017-06-27 14:25 UTC, tukeJonny commented on common/util.go
> +	//check
消しましたー

2017-06-27 14:25 UTC, tukeJonny commented on common/util_test.go
> +	// Open json_file for testing
消しましたー

2017-06-27 14:25 UTC, tukeJonny commented on common/util_test.go
> +	// Create HTTP Response
少し試しに詳しく書いてみました。
また確認お願いしますー

2017-06-27 14:26 UTC, tukeJonny commented on ctftime/event.go
> +	url := URL_PREFIX + "/events/?limit=" + strconv.Itoa(LIMIT) + "&start=" + strconv.FormatInt(now, 10)
fmt.Sprintf("%d", LIMIT)に変更しましたー

2017-06-27 14:26 UTC, tukeJonny commented on ctftime/event_test.go
> +	"github.com/tukejonny/g0tiu5a-bot/common"
修正しましたー

2017-06-28 01:00 UTC, ryosan-470 commented
[![LGTM](http://lgtm.in/p/MmJa8s8oq)](http://lgtm.in/i/MmJa8s8oq)

2017-06-28 01:01 UTC, ryosan-470 approved these changes

2017-06-28 01:01 UTC, merged